// Solid-ToDo/src/App.tsx
import { createSignal, For } from "solid-js";
import "./App.css";

function App() {
  const [todos, setToDos] = createSignal([
    {
      title: "Make this",
      check: true,
    },
  ]);

  const [title, setTitle] = createSignal("Awesome");

  function Add() {
    setToDos(
      todos().concat([
        {
          title: title(),
          check: false,
        },
      ])
    );
  }

  function Del(index: number) {
    setToDos(todos().filter((_c, i) => i !== index));
  }

  return (
    <>
      <div>
        <input
          type="text"
          value={title()}
          onInput={(e) => setTitle(e.currentTarget.value)}
        />
        <button onClick={Add}>Add</button>
        <For each={todos()}>
          {(todo, index) => {
            return (
              <div class="todo">
                <h2>{todo.title}</h2> {/* Todo line-through */}
                <input
                  type="checkbox"
                  checked={todo.check}
                  onChange={() => {
                    const updatedTodos = todos().slice();
                    updatedTodos[index()].check = !updatedTodos[index()].check;
                    setToDos(updatedTodos);
                  }}
                />
                <button
                  onClick={() => {
                    Del(index());
                  }}
                >
                  Del
                </button>
              </div>
            );
          }}
        </For>
      </div>
    </>
  );
}

export default App;

// React-ToDo/src/App.tsx
import { ReactNode, useState } from "react";
import "./App.css";

function App() {
  const [todos, setTodos] = useState([
    {
      title: "Make this",
      check: true,
    },
  ]);

  const [title, setTitle] = useState("Awesome");

  function handleAdd() {
    setTodos([...todos, { title, check: false }]);
  }

  function handleDelete(index: number) {
    const newTodos = todos.filter((_c, i) => i !== index);
    setTodos(newTodos);
  }

  function handleToggleCheck(index: number) {
    const updatedTodos = todos.map((todo, i) =>
      i === index ? { ...todo, check: !todo.check } : todo
    );
    setTodos(updatedTodos);
  }

  return (
    <>
      <div>
        <input
          value={title}
          onChange={(e) => {
            setTitle(e.target.value);
          }}
        />
        <button onClick={handleAdd}>Add</button>
        <div className="todo-box">
          {todos.map((todo, index) => (
            <div className="todos" key={index}>
              <h2
                style={{
                  textDecoration: todo.check ? "line-through" : "none",
                }}
              >
                {todo.title}
              </h2>
              <input
                type="checkbox"
                checked={todo.check}
                onChange={() => {
                  handleToggleCheck(index);
                }}
              />
              <button onClick={() => handleDelete(index)}>Del</button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

export default App;
