// Angular-Todo/src/app/app.component.ts
import { Component, SimpleChange } from '@angular/core';
import { TodosService } from './todos.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  constructor(public todos: TodosService) {}

  title = 'awesome';

  toggleCheck(index: number) {
    this.todos.todos[index].check = !this.todos.todos[index].check;
  }

  deleteTodo(index: number) {
    this.todos.todos = this.todos.todos.filter((n, i) => i !== index);;
  }

  add(title: string) {
    this.todos.todos.push({
      title,
      check: false,
    });
  }
}

<div>
  <div>
    <input type="text" [(ngModel)]="title" [value]="title" />
    <app-add [title]="title" (addEvent)="add($event)"></app-add>
  </div>
  <div>
    <div *ngFor="let todo of todos['todos'];
    let i = index;
    " class="todos">
      <h2 [style]="'text-decoration: ' + (todo.check ? 'line-through' : '')  ">{{ todo.title }}</h2>
      <input type="checkbox" [checked]="todo.check" (click)="toggleCheck(i)"/>
      <button (click)="deleteTodo(i)">Del</button>
    </div>
  </div>
</div>

// Solid-ToDo/src/App.tsx
import { createSignal, For } from "solid-js";
import "./App.css";

function App() {
  const [todos, setToDos] = createSignal([
    {
      title: "Make this",
      check: true,
    },
  ]);

  const [title, setTitle] = createSignal("Awesome");

  function Add() {
    setToDos(
      todos().concat([
        {
          title: title(),
          check: false,
        },
      ])
    );
  }

  function Del(index: number) {
    setToDos(todos().filter((_c, i) => i !== index));
  }

  return (
    <>
      <div>
        <input
          type="text"
          value={title()}
          onInput={(e) => setTitle(e.currentTarget.value)}
        />
        <button onClick={Add}>Add</button>
        <For each={todos()}>
          {(todo, index) => {
            return (
              <div class="todo">
                <h2>{todo.title}</h2> {/* Todo line-through */}
                <input
                  type="checkbox"
                  checked={todo.check}
                  onChange={() => {
                    const updatedTodos = todos().slice();
                    updatedTodos[index()].check = !updatedTodos[index()].check;
                    setToDos(updatedTodos);
                  }}
                />
                <button
                  onClick={() => {
                    Del(index());
                  }}
                >
                  Del
                </button>
              </div>
            );
          }}
        </For>
      </div>
    </>
  );
}

export default App;
